name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '**.md'
      - app/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew fingerprint:lint

      - name: Test
        run: ./gradlew fingerprint:test

      - name: Build
        run: ./gradlew fingerprint:assemble